"""T1000 Entropy Layer schemas."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field, model_validator


class AlertType(str, Enum):
    """Kind of entropy alert generated by the detector."""

    KL_THRESHOLD = "kl_threshold"
    ENTROPY_GRADIENT = "entropy_gradient"


class EntropyAlert(BaseModel):
    """Single alert event emitted by the entropy detector.

    triggered_at:
        Step index at which the alert condition was detected.
    alert_type:
        KL_THRESHOLD if KL divergence crossed the configured threshold;
        ENTROPY_GRADIENT if the rolling entropy rate gradient triggered.
    metric_value:
        The KL divergence or gradient value that caused the alert.
    threshold:
        The configured threshold that was exceeded.
    """

    experiment_id: str = Field(..., pattern=r"^exp-\d+$")
    triggered_at: int = Field(..., ge=0)
    alert_type: AlertType
    metric_value: float
    threshold: float
    message: str = ""
    produced_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class EntropyReport(BaseModel):
    """Aggregated entropy monitoring output for one experiment run (T1000).

    entropy_series:
        Shannon entropy H_t at each observation step.
    kl_series:
        KL divergence KL(posterior_t || prior) at each step.
    entropy_rate_series:
        Rolling mean of ΔH_t = H_t − H_{t−1}.  Length is
        len(entropy_series) − 1 (first differences).
    alerts:
        All alerts fired during monitoring.
    """

    experiment_id: str = Field(..., pattern=r"^exp-\d+$")
    entropy_series: list[float] = Field(..., min_length=1)
    kl_series: list[float] = Field(..., min_length=1)
    entropy_rate_series: list[float] = Field(default_factory=list)
    alerts: list[EntropyAlert] = Field(default_factory=list)
    produced_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def series_lengths_consistent(self) -> EntropyReport:
        if len(self.kl_series) != len(self.entropy_series):
            raise ValueError(
                f"kl_series length ({len(self.kl_series)}) must equal "
                f"entropy_series length ({len(self.entropy_series)})"
            )
        return self
