"""Phase-space reconstruction and maximum Lyapunov exponent for GNSS signals.

Theory
------
Takens' embedding theorem (1981) guarantees that the attractor of a dynamical
system can be reconstructed from a single scalar observable x(t) by forming
delay-coordinate vectors:

    y(t) = [x(t), x(t − τ), ..., x(t − (m−1)τ)]   ∈ ℝᵐ

where m is the *embedding dimension* and τ is the *time delay*.

The maximum Lyapunov exponent λ₁ measures the average exponential rate at
which nearby trajectories diverge.  For a chaotic attractor λ₁ > 0.

Spoofing detection rationale
-----------------------------
Genuine GNSS signals exhibit mild chaos (λ₁ slightly positive) due to
satellite orbital dynamics, atmospheric turbulence, and receiver noise.
A spoofed signal is generated by a single transmitter, making it nearly
deterministic (λ₁ ≈ 0 or negative).  A sudden drop in λ₁ from a positive
baseline therefore indicates injection of an artificial signal.

Algorithm: Rosenstein et al. (1993)
------------------------------------
1. Embed x(t) into ℝᵐ using delay τ.
2. For each point j, find its nearest neighbour nn(j) (excluding points
   within a Theiler window W_T of j to avoid temporal correlation).
3. Track divergence over i = 1..max_iter steps:
       d_j(i) = |y(t_j + i) − y(t_{nn(j)} + i)|
4. Average log-divergence:
       S(i) = ⟨ln d_j(i)⟩_j   (mean over all valid j at step i)
5. Maximum Lyapunov exponent:
       λ₁ = slope of S(i) vs i  [units: nats per sample]
   In physical units: λ₁ / dt  [bits per second or nats per second].

Refs:
    Takens, F. (1981). Detecting strange attractors in turbulence.
    Rosenstein, M., Collins, J., De Luca, C. (1993).
        A practical method for calculating largest Lyapunov exponents
        from small data sets. Physica D, 65(1–2), 117–134.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# ---------------------------------------------------------------------------
# Module constants
# ---------------------------------------------------------------------------

EMBED_DIM: int = 3  # embedding dimension m (conservative for GNSS)
TIME_DELAY: int = 1  # delay τ in samples
THEILER_WINDOW: int = 5  # minimum temporal separation for nearest neighbour
MAX_ITER: int = 20  # maximum divergence tracking steps
MIN_POINTS: int = 50  # minimum embedded points for reliable λ₁ estimate
LYA_ALARM_THRESH: float = 0.05  # λ₁ ≤ thresh → near-deterministic → spoofing alarm

# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PhaseSpaceResult:
    """Output of the phase-space Lyapunov exponent estimator.

    Fields
    ------
    n_points        Number of embedded delay-vectors used.
    lambda_max      Estimated maximum Lyapunov exponent λ₁ [nats/sample].
    divergence_curve  S(i) array of length max_iter (raw average log-divergence).
    alarm           True when λ₁ ≤ LYA_ALARM_THRESH (non-chaotic signal).
    reason          Short status string.
    """

    n_points: int
    lambda_max: float
    divergence_curve: np.ndarray
    alarm: bool
    reason: str


# ---------------------------------------------------------------------------
# Delay-embedding
# ---------------------------------------------------------------------------


def takens_embed(
    x: np.ndarray,
    m: int = EMBED_DIM,
    tau: int = TIME_DELAY,
) -> np.ndarray:
    """Construct Takens delay-embedding of scalar time series x.

    Args:
        x:   1-D array of shape (N,).
        m:   Embedding dimension.
        tau: Time delay (in samples).

    Returns:
        Y: array of shape (N − (m−1)·τ, m) — each row is one delay vector.

    Raises:
        ValueError: if x is too short for the requested m and tau.
    """
    x = np.asarray(x, dtype=float)
    if x.ndim != 1:
        raise ValueError("x must be 1-D.")
    n_out = len(x) - (m - 1) * tau
    if n_out < 1:
        raise ValueError(
            f"Time series too short: need at least {(m - 1) * tau + 1} points "
            f"for m={m}, tau={tau}, got {len(x)}."
        )
    rows = [x[i * tau : i * tau + n_out] for i in range(m)]
    return np.column_stack(rows)  # (n_out, m)


# ---------------------------------------------------------------------------
# Maximum Lyapunov exponent (Rosenstein 1993)
# ---------------------------------------------------------------------------


def max_lyapunov_exponent(
    x: np.ndarray,
    m: int = EMBED_DIM,
    tau: int = TIME_DELAY,
    theiler_window: int = THEILER_WINDOW,
    max_iter: int = MAX_ITER,
) -> PhaseSpaceResult:
    """Estimate the maximum Lyapunov exponent λ₁ via Rosenstein (1993).

    Args:
        x:              1-D scalar time series (e.g. Doppler deviation or C/N₀).
        m:              Embedding dimension.
        tau:            Time delay in samples.
        theiler_window: Minimum index separation for nearest-neighbour search.
        max_iter:       Number of divergence-tracking steps.

    Returns:
        PhaseSpaceResult with lambda_max, divergence_curve, and alarm flag.
    """
    x = np.asarray(x, dtype=float)

    # --- Phase space reconstruction ---
    try:
        Y = takens_embed(x, m=m, tau=tau)
    except ValueError as exc:
        return PhaseSpaceResult(
            n_points=0,
            lambda_max=float("nan"),
            divergence_curve=np.array([]),
            alarm=False,
            reason=f"embed_failed: {exc}",
        )

    n = len(Y)
    if n < MIN_POINTS:
        return PhaseSpaceResult(
            n_points=n,
            lambda_max=float("nan"),
            divergence_curve=np.array([]),
            alarm=False,
            reason=f"too_few_points: {n} < {MIN_POINTS}",
        )

    # --- Nearest-neighbour search (brute-force, O(n²)) ---
    # Pairwise squared distances
    diff = Y[:, None, :] - Y[None, :, :]  # (n, n, m)
    sq_dist = np.sum(diff**2, axis=-1)  # (n, n)

    # Exclude self and Theiler window
    mask = np.abs(np.arange(n)[:, None] - np.arange(n)[None, :]) <= theiler_window
    sq_dist[mask] = np.inf

    nn_idx = np.argmin(sq_dist, axis=1)  # (n,) nearest neighbour indices

    # --- Divergence tracking ---
    # For each pair (j, nn(j)), track |Y[j+i] - Y[nn(j)+i]| over i steps.
    actual_max_iter = min(max_iter, n - 1)
    sum_log_div = np.zeros(actual_max_iter, dtype=float)
    count = np.zeros(actual_max_iter, dtype=int)

    for j in range(n):
        nn_j = nn_idx[j]
        for i in range(1, actual_max_iter + 1):
            ji = j + i
            nn_ji = nn_j + i
            if ji >= n or nn_ji >= n:
                break
            d = float(np.linalg.norm(Y[ji] - Y[nn_ji]))
            if d > 0:
                sum_log_div[i - 1] += np.log(d)
                count[i - 1] += 1

    # Average log-divergence (S(i)), only where count > 0
    valid = count > 0
    S = np.full(actual_max_iter, float("nan"))
    S[valid] = sum_log_div[valid] / count[valid]

    # --- Linear fit: λ₁ = slope of S(i) vs i ---
    valid_idx = np.where(valid)[0].astype(float)
    if len(valid_idx) < 2:
        return PhaseSpaceResult(
            n_points=n,
            lambda_max=float("nan"),
            divergence_curve=S,
            alarm=False,
            reason="insufficient_divergence_data",
        )

    slope, _ = np.polyfit(valid_idx, S[valid], 1)
    lambda_max = float(slope)

    alarm = lambda_max <= LYA_ALARM_THRESH
    reason = "ok" if not alarm else f"lambda_max={lambda_max:.4f}<=0_non_chaotic"

    return PhaseSpaceResult(
        n_points=n,
        lambda_max=lambda_max,
        divergence_curve=S,
        alarm=alarm,
        reason=reason,
    )
